import { getRandomColor } from "@/utils";
import icon from "@/assets/amongus.png";

export const users = [
  {
    userId: "1",
    name: "Eric",
    userName: "eric54",
    userRegistrationDate: "07.07.2018",
    avatar: icon,
    role: "role-1",
    note: "",
    status: "idle",
    serverRegistrationDate: "09.09.2023",
    serverName: "Bounderies",
    backgroundBanner: getRandomColor(),
  },
  {
    userId: "2",
    name: "Stan",
    userName: "stan854",
    userRegistrationDate: "07.07.2017",
    avatar: null,
    role: "role-1",
    status: "offline",
    serverRegistrationDate: "09.09.2023",
    serverName: "Bounderies",
    note: "",
    backgroundBanner: getRandomColor(),
  },
  {
    userId: "3",
    name: "Wendy",
    userName: "wendy033",
    userRegistrationDate: "07.10.2020",
    avatar: null,
    role: "role-2",
    status: "idle",
    serverRegistrationDate: "09.09.2023",
    serverName: "Bond",
    note: "",
    backgroundBanner: getRandomColor(),
  },
  {
    userId: "4",
    name: "Kenny",
    userName: "007kenny",
    userRegistrationDate: "07.27.2021",
    avatar: null,
    role: "role-2",
    status: "invisible",
    serverRegistrationDate: "09.09.2023",
    serverName: "Ks",
    note: "",
    backgroundBanner: getRandomColor(),
  },
  {
    userId: "5",
    name: "Kyle",
    userName: "ekyle54",
    userRegistrationDate: "07.03.2022",
    serverName: "Mono",
    avatar: null,
    role: null,
    status: "offline",
    serverRegistrationDate: "09.09.2023",
    note: "",
    backgroundBanner: getRandomColor(),
  },
  {
    userId: "6",
    name: "Chef",
    userName: "chef80",
    userRegistrationDate: "12.17.2019",
    serverName: "Bond",
    avatar: null,
    role: null,
    status: "online",
    serverRegistrationDate: "09.09.2023",
    note: "",
    backgroundBanner: getRandomColor(),
  },
];
