import { getRandomColor } from "@/utils";
import icon from "@/assets/amongus.png";
import { Status } from ".";

export const SAMPLE_CHANNELS = [
  { id: "1", name: "general", type: "text" },
  { id: "2", name: "voice", type: "voice" },
  { id: "3", name: "random", type: "text" },
  { id: "4", name: "music", type: "voice" },
];

const SAMPLE_SERVER_TITLE = "default";

export const SAMPLE_USERS = [
  {
    userId: "1",
    name: "Ernest",
    userName: "ernesthemingway",
    userRegistrationDate: "07.07.2018",
    avatar: icon,
    role: "role-1",
    note: "",
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    serverName: SAMPLE_SERVER_TITLE,
    bannerColor: getRandomColor(),
  },
  {
    userId: "2",
    name: "Ian",
    userName: "fleming",
    userRegistrationDate: "07.07.2017",
    avatar: null,
    role: "role-1",
    status: Status.IDLE,
    serverRegistrationDate: "09.09.2023",
    serverName: SAMPLE_SERVER_TITLE,
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "3",
    name: "Charles",
    userName: "dickens1812",
    userRegistrationDate: "07.10.2020",
    avatar: null,
    role: "role-2",
    status: Status.INVISIBLE,
    serverRegistrationDate: "09.09.2023",
    serverName: SAMPLE_SERVER_TITLE,
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "4",
    name: "George",
    userName: "gorwell",
    userRegistrationDate: "07.27.2021",
    avatar: null,
    role: "role-2",
    status: Status.INVISIBLE,
    serverRegistrationDate: "09.09.2023",
    serverName: SAMPLE_SERVER_TITLE,
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "5",
    name: "Edgar",
    userName: "allanpoe",
    userRegistrationDate: "07.03.2022",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.OFFLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "6",
    name: "Arthur",
    userName: "thesirconandoyle",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "7",
    name: "Jack",
    userName: "jlondon76",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "8",
    name: "Agatha",
    userName: "christie",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "9",
    name: "William",
    userName: "wshakespeare",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "10",
    name: "Francis",
    userName: "fscottfitzgerald",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "11",
    name: "Mark",
    userName: "marktwain",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "12",
    name: "Jerome",
    userName: "jeromeselinger",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "13",
    name: "Heather",
    userName: "heathermorris",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "14",
    name: "Oscar",
    userName: "oscarwilde",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "15",
    name: "Charlotte",
    userName: "charlottebronte",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "16",
    name: "Herper",
    userName: "harperlee",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
  {
    userId: "17",
    name: "Jane",
    userName: "janeeyre",
    userRegistrationDate: "12.17.2019",
    serverName: SAMPLE_SERVER_TITLE,
    avatar: null,
    role: null,
    status: Status.ONLINE,
    serverRegistrationDate: "09.09.2023",
    note: "",
    bannerColor: getRandomColor(),
  },
];
export const SAMPLE_MESSAGES = [
  {
    ...SAMPLE_USERS[0],
    messageID: 1,
    timestamp: 1694970000000,
    text: "Hey :)",
  },
  {
    ...SAMPLE_USERS[1],
    messageID: 2,
    timestamp: 1694970600000,
    text: "Hello.",
  },
  {
    ...SAMPLE_USERS[2],
    messageID: 3,
    timestamp: 1694970700000,
    text: "hi",
  },
  {
    ...SAMPLE_USERS[3],
    messageID: 4,
    timestamp: 1694970800000,
    text: "Howdy",
  },
  {
    ...SAMPLE_USERS[4],
    messageID: 5,
    timestamp: 1694970900000,
    text: "What's up?",
  },
  {
    ...SAMPLE_USERS[5],
    messageID: 6,
    timestamp: 1694971000000,
    text: "Salutations!",
  },
];

export const SAMPLE_SERVER = {
  id: "1",
  title: SAMPLE_SERVER_TITLE,
  channels: SAMPLE_CHANNELS,
  users: SAMPLE_USERS,
};
